name: Build Module

on: 
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-tags: true
                fetch-depth: 0

            - name: Install modules
              shell: pwsh
              run : |
                Install-Module -Name ModuleBuilder -Force

            - name: Build module
              shell: pwsh
              run : |
                $v = git describe --tags --abbrev=0
                Write-Host "Git Tag: [$($v)]"
                . ./build-scripts/Start-ModuleBuild.ps1 -version $v

            - uses: actions/upload-artifact@v4
              with:
                path: build/**
